version: "3.8"

services:
  geth:
    image: ethereum/client-go:stable
    container_name: eth-execution
    stop_signal: SIGINT
    stop_grace_period: 2m
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "18545:8545"
      - "18546:8546"
    volumes:
      - ./eth-data/execution:/root/.ethereum
      - ./jwt/jwt.hex:/jwt/jwt.hex:ro
    command:
      - --mainnet
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,debug
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3,debug
      - --ws.origins=*
      - --syncmode=snap
      - --snapshot=true
      - --cache=4096
      - --authrpc.jwtsecret=/jwt/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: eth-consensus
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 1m
    ports:
      - "9000:9000"
      - "9000:9000/udp"
    #  - "5052:5052"
    volumes:
      - ./eth-data/consensus:/root/.lighthouse
      - ./jwt/jwt.hex:/jwt/jwt.hex:ro
    command:
      - lighthouse
      - bn
      - --network=mainnet
      - --execution-endpoint=http://eth-execution:8551
      - --execution-jwt=/jwt/jwt.hex
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --checkpoint-sync-url=https://sync-mainnet.beaconcha.in
      - --disable-deposit-contract-sync
      - --prune-payloads=true
    depends_on:
      - geth
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"