global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lighthouse'
    metrics_path: /metrics
    static_configs:
      - targets: ['lighthouse:5054']
        labels:
          instance: lighthouse

  - job_name: 'geth'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['geth:6060']
        labels:
          instance: geth

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus